# Generated by Django 3.2.4 on 2021-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('fornecedor', models.CharField(max_length=200)),
                ('qnt_em_estoque', models.PositiveIntegerField()),
                ('preco_de_venda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
