# Generated by Django 3.2.4 on 2021-06-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_auto_20210610_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Produtos.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='produtos',
            field=models.ManyToManyField(through='Produtos.ProdutosCategoria', to='Produtos.Produto'),
        ),
    ]
