# Generated by Django 3.2.4 on 2021-06-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0003_auto_20210610_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoscategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produtoscategoria',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='ProdutosCategoria',
        ),
    ]
