# Generated by Django 3.2.4 on 2021-06-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0005_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome', 'fornecedor']},
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(max_length=200, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_de_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qnt_em_estoque',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade em estoque'),
        ),
    ]
