# Generated by Django 3.2.4 on 2021-07-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0007_auto_20210712_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='secao',
        ),
    ]
