# Generated by Django 3.2.4 on 2021-07-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0008_rename_categoria_produto_secao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='secao',
        ),
        migrations.DeleteModel(
            name='Secao',
        ),
    ]
