# Generated by Django 3.2.4 on 2021-07-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0009_auto_20210712_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto'),
        ),
    ]
