# Generated by Django 3.2.4 on 2021-07-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0010_produto_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desconto',
        ),
    ]
