# Generated by Django 3.2.4 on 2021-07-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0012_produto_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
